---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(mgcv)
library(lubridate)
library(readxl)

replace_comma <- function(values){
    values_parsed <- values %>% as.character() %>% parse_number(locale = locale(decimal_mark = ","))
}
```



```{r}
mtransp<-read_excel("Jordbruk_analysvärden.xls", sheet="Analysvärden", skip=2, guess_max=20000)%>%filter(ID=="H29", Provtyp=="Manuellt prov")%>%
  mutate_at(c( "Totalkväve_mg/l", "Totalfosfor_mg/l"),replace_comma)%>%
  mutate(logTN=log(`Totalkväve_mg/l`), logTP=log(`Totalfosfor_mg/l`),Year=as.numeric(substr(Datum, 1,4)), Month=as.numeric(substr(Datum, 6,7)), Day=as.numeric(substr(Datum, 9,10)))

disch<-read_excel("Vattenföring_H-län_210323.xls", sheet="Vattenföring", skip=2, guess_max=100000)%>%filter(ID=="H29")%>%
   mutate_at(c("Dygnsmedelflöde_l/s"),replace_comma)%>%
  mutate(logq=log(`Dygnsmedelflöde_l/s`), Year=as.numeric(substr(Datum, 1, 4)), Month=as.numeric(substr(Datum, 6,7)), Day=as.numeric(substr(Datum, 9,10)))%>%
  filter(!(`Dygnsmedelflöde_l/s`==0))

H29<-mtransp%>%left_join(disch)%>%mutate(Date=as.Date( paste(Month, Day , Year , sep = "." )  , format = "%m.%d.%Y"), dec.date=decimal_date(Date), dec.during=dec.date-year(Date))


```
```{r}
H29mod_without<-lm(logTN~logq, data=H29)
summary(H29mod_without)

H29mod_withtrend<-gamm(logTN~s(dec.date)+logq, correlation=corCAR1(form = ~dec.date),method="REML", data=H29)

summary(H29mod_withtrend$gam)
```




```{r}
H29_mod<-gamm(logTN~te(Year, dec.during, bs=c("cr", "cc")) +te(Year, dec.during, by=logq,  bs=c("cr", "cc")),correlation=corCAR1(form=~dec.date),data=H29, method="REML")

C6_mod<-gamm(logTN~te(Year, dec.during) +te(Year, dec.during, by=logq),correlation=corCAR1(form=~dec.date),data=C6, method="REML")


H29_mod<-gamm(logTP~te(Year, dec.during, bs=c("cr", "cc")) +te(Year, dec.during, by=logq,  bs=c("cr", "cc")),data=H29, method="REML")

C6_mod<-gamm(logTP~te(Year, dec.during) +te(Year, dec.during, by=logq),correlation=corCAR1(form=~dec.date),data=C6, method="REML")

terms29<-predict.gam(H29_mod$gam, type="terms", newdata=H29, se.fit=TRUE)

vis.gam(H29_mod$gam, plot.type="contour")


H29$fit<-terms29$fit[,1]+attr(terms29, "constant")
H29$fit.upper<-H29$fit+1.96*terms29$se.fit[,1]
H29$fit.lower<-H29$fit-1.96*terms29$se.fit[,1]
H29$coeff<-terms29$fit[,2]/H29$logq
H29$coeff.upper<-H29$coeff+1.96*terms29$se.fit[,2]/abs(H29$logq)
H29$coeff.lower<-H29$coeff-1.96*terms29$se.fit[,2]/abs(H29$logq)


#new<-expand.grid(dec.during=seq(0,1, length.out=50), logq=seq(min(N34$logq),max(N34$logq), length.out=50), Year=seq(min(N34$Year), max(N34$Year), length.out=50))


new<-expand.grid(dec.during=seq(0,1, length.out=50), logq=rep(1, 50), Year=seq(min(H29$Year), max(H29$Year), length.out=50))

terms_new<-predict.gam(H29_mod$gam, type="terms", newdata=new, se.fit=TRUE)
#terms_new1<-predict.gam(N34_mod$gam, type="response", exclude=c("te(year)", "te(decimal_during)"), newdata=new, se.fit=TRUE)

new$terms<-terms_new$fit[,1]+attr(terms29, "constant")
new$coeff<-terms_new$fit[,2]
new$cont_month=new$dec.during*12+1
new
new$Month=floor(new$cont_month)
new$coeff.upper<-new$coeff+1.96*terms_new$se.fit[,2]
new$coeff.lower<-new$coeff-1.96*terms_new$se.fit[,2]

new%>%
ggplot(aes(x=Year, y=cont_month, z=coeff)) +
  stat_contour_filled()+
  xlab("Year")+
  theme_bw()+
  scale_y_continuous(name="Month", breaks=c(1,3,5,7,9,11))+
  labs(fill = "Regression coefficient")
```


Enskild månad med standard error.

```{r}
new%>%filter(cont_month>8.4 & cont_month<8.6)%>%
  ggplot( aes(Year, coeff,coeff.lower,coeff.upper)) +
  geom_line(aes(y = coeff), color="red", lwd=2)+
  geom_line(aes(y = coeff.lower))+
  geom_line(aes(y = coeff.upper))+
  ylab("Regression coefficient")+
  geom_ribbon(aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")+
  theme_bw()



new%>%filter(cont_month>2.4 & cont_month<2.6)%>%
  ggplot( aes(Year, coeff,coeff.lower,coeff.upper)) +
  geom_line(aes(y = coeff), color="red", lwd=2)+
  geom_line(aes(y = coeff.lower))+
  geom_line(aes(y = coeff.upper))+
  ylab("Regression coefficient")+
  geom_ribbon(aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")+
  theme_bw()


new%>%filter(cont_month>8.4 & cont_month<8.6)%>%
  ggplot( aes(Year, coeff,coeff.lower,coeff.upper)) +
  geom_line(aes(y = coeff), color="red", lwd=2)+
  geom_line(aes(y = coeff.lower))+
  geom_line(aes(y = coeff.upper))+
  ylab("Regression coefficient")+
  geom_ribbon(aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")+
  theme_bw()+
geom_line(data=new%>%filter(cont_month>2.4 & cont_month<2.6),aes(y = coeff), color="blue", lwd=2)+
    geom_line(data=new%>%filter(cont_month>2.4 & cont_month<2.6),aes(y = coeff.lower))+
  geom_line(data=new%>%filter(cont_month>2.4 & cont_month<2.6),aes(y = coeff.upper))+
  geom_ribbon(data=new%>%filter(cont_month>2.4 & cont_month<2.6),aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")



new%>%filter(cont_month>2.4 & cont_month<2.6)%>%
  ggplot( aes(Year, coeff,coeff.lower,coeff.upper)) +
  geom_line(aes(y = coeff), color="red", lwd=2)+
  geom_line(aes(y = coeff.lower))+
  geom_line(aes(y = coeff.upper))+
  ylab("Regression coefficient")+
  geom_ribbon(aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")+
  theme_bw()


new%>%filter(cont_month>7.2 & cont_month<7.4)%>%
  ggplot( aes(Year, coeff,coeff.lower,coeff.upper)) +
  geom_line(aes(y = coeff), color="red", lwd=2)+
  geom_line(aes(y = coeff.lower))+
  geom_line(aes(y = coeff.upper))+
  ylab("Regression coefficient")+
  geom_ribbon(aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")+
  theme_bw()+
geom_line(data=new%>%filter(cont_month>1.1 & cont_month<1.3),aes(y = coeff), color="blue", lwd=2)+
    geom_line(data=new%>%filter(cont_month>1.4 & cont_month<1.6),aes(y = coeff.lower))+
  geom_line(data=new%>%filter(cont_month>1.4 & cont_month<1.6),aes(y = coeff.upper))+
  geom_ribbon(data=new%>%filter(cont_month>1.4 & cont_month<1.6),aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")


```


```{r}
new%>%
ggplot(aes(x=Year, y=cont_month, z=terms)) +
  stat_contour_filled()+
  ylab("Month")+
  xlab("Year")+
  theme_bw()
  


ggplot(H29, aes(Date, fit,fit.lower,fit.upper, logTN)) +
  geom_line(aes(y = fit), color="red", lwd=2)+
  geom_line(aes(y = fit.lower))+
  geom_line(aes(y = fit.upper))+
  geom_point(aes(y=logTN))+
  ylab("Total nitrogen on the log-scale")+
  geom_ribbon(aes(ymin=fit.lower, ymax=fit.upper),alpha=0.09, fill = "blue")

ggplot(H29, aes(Date, coeff,coeff.lower,coeff.upper)) +
  geom_line(aes(y = coeff), color="red", lwd=2)+
  geom_line(aes(y = coeff.lower))+
  geom_line(aes(y = coeff.upper))+
  ylab("Regression coefficient")+
  geom_ribbon(aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")+
  theme_bw()


ggplot(H29, aes(Date, logTN))+
  geom_point()+
  geom_line(aes(x=Date, y=logq))

ggplot(H29, aes(logq, logTN,col=as.factor(Month)))+
  geom_point()+
  geom_smooth(method="lm")
```

Only year

```{r}
H29_mod_year<-gamm(logTN~te(dec.date) +te(dec.date, by=logq),correlation=corCAR1(form=~dec.date),data=H29, method="REML")


terms1d<-predict.gam(H29_mod_year$gam, type="terms", newdata=H29, se.fit=TRUE)

H29$fit<-terms1d$fit[,1]+attr(terms1d, "constant")#+mean(terms1d$fit[,2], na.rm=TRUE)
H29$fit.upper<-H29$fit+1.96*terms1d$se.fit[,1]
H29$fit.lower<-H29$fit-1.96*terms1d$se.fit[,1]
H29$coeff<-terms1d$fit[,2]/H29$logq
H29$coeff.upper<-H29$coeff+1.96*terms1d$se.fit[,2]/abs(H29$logq)
H29$coeff.lower<-H29$coeff-1.96*terms1d$se.fit[,2]/abs(H29$logq)




ggplot(H29, aes(dec.date, logTN,fit,fit.lower,fit.upper)) +
  geom_point(aes(x=dec.date, y=logTN))+
  geom_line(aes(y = fit), color="red", lwd=2)+
 # geom_line(aes(y = fit.lower))+
#  geom_line(aes(y = fit.upper))+
  ylab("log-transformed total nitrogen")+
  xlab("Date")+
  #geom_ribbon(aes(ymin=fit.lower, ymax=fit.upper),alpha=0.09, fill = "blue")+
  theme_bw()+
  theme(text= element_text(size = 16))


ggplot(H29, aes(dec.date, coeff,coeff.lower,coeff.upper)) +
  geom_line(aes(y = coeff), color="red", lwd=2)+
  geom_line(aes(y = coeff.lower))+
  geom_line(aes(y = coeff.upper))+
  ylab("Regression coefficient")+
  xlab("Date")+
  geom_ribbon(aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")+
  theme_bw()+
  theme(text= element_text(size = 16))
```


```{r}

H29%>%filter(Month==7 | Month==8 | Month==9)->H29_summ

H29_mod_year<-gamm(logTN~te(dec.date) +te(dec.date, by=logq),correlation=corCAR1(form=~dec.date),data=H29_summ, method="REML")


terms1d<-predict.gam(H29_mod_year$gam, type="terms", newdata=H29_summ, se.fit=TRUE)

H29_summ$fit<-terms1d$fit[,1]+attr(terms1d, "constant")+terms1d$fit[,2]/H29_summ$logq*mean(H29_summ$logq, na.rm=TRUE)
H29_summ$fit.upper<-H29_summ$fit+1.96*terms1d$se.fit[,1]
H29_summ$fit.lower<-H29_summ$fit-1.96*terms1d$se.fit[,1]
H29_summ$coeff<-terms1d$fit[,2]/H29_summ$logq
H29_summ$coeff.upper<-H29_summ$coeff+1.96*terms1d$se.fit[,2]/abs(H29_summ$logq)
H29_summ$coeff.lower<-H29_summ$coeff-1.96*terms1d$se.fit[,2]/abs(H29_summ$logq)




ggplot(H29_summ, aes(dec.date, logTN,fit,fit.lower,fit.upper)) +
  geom_point(aes(x=dec.date, y=logTN))+
  geom_line(aes(y = fit), color="red", lwd=2)+
 # geom_line(aes(y = fit.lower))+
#  geom_line(aes(y = fit.upper))+
  ylab("log-transformed total nitrogen")+
  xlab("Date")+
  #geom_ribbon(aes(ymin=fit.lower, ymax=fit.upper),alpha=0.09, fill = "blue")+
  theme_bw()+
  theme(text= element_text(size = 16))


ggplot(H29_summ, aes(dec.date, coeff,coeff.lower,coeff.upper)) +
  geom_line(aes(y = coeff), color="red", lwd=2)+
  geom_line(aes(y = coeff.lower))+
  geom_line(aes(y = coeff.upper))+
  ylab("Regression coefficient")+
  xlab("Date")+
  geom_ribbon(aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")+
  theme_bw()+
  theme(text= element_text(size = 16))
```

```{r}
H29%>%filter(Month==1 | Month==2 | Month==3)->H29_summ

H29_mod_year<-gamm(logTN~te(dec.date) +te(dec.date, by=logq),correlation=corCAR1(form=~dec.date),data=H29_summ, method="REML")


terms1d<-predict.gam(H29_mod_year$gam, type="terms", newdata=H29_summ, se.fit=TRUE)

H29_summ$fit<-terms1d$fit[,1]+attr(terms1d, "constant") + terms1d$fit[,2]/H29_summ$logq*mean(H29_summ$logq, na.rm=TRUE)
H29_summ$fit.upper<-H29_summ$fit+1.96*terms1d$se.fit[,1]
H29_summ$fit.lower<-H29_summ$fit-1.96*terms1d$se.fit[,1]
H29_summ$coeff<-terms1d$fit[,2]/H29_summ$logq
H29_summ$coeff.upper<-H29_summ$coeff+1.96*terms1d$se.fit[,2]/abs(H29_summ$logq)
H29_summ$coeff.lower<-H29_summ$coeff-1.96*terms1d$se.fit[,2]/abs(H29_summ$logq)




ggplot(H29_summ, aes(dec.date, logTN,fit,fit.lower,fit.upper)) +
  geom_point(aes(x=dec.date, y=logTN))+
  geom_line(aes(y = fit), color="red", lwd=2)+
 # geom_line(aes(y = fit.lower))+
#  geom_line(aes(y = fit.upper))+
  ylab("log-transformed total nitrogen")+
  xlab("Date")+
  #geom_ribbon(aes(ymin=fit.lower, ymax=fit.upper),alpha=0.09, fill = "blue")+
  theme_bw()+
  theme(text= element_text(size = 16))


ggplot(H29_summ, aes(dec.date, coeff,coeff.lower,coeff.upper)) +
  geom_line(aes(y = coeff), color="red", lwd=2)+
  geom_line(aes(y = coeff.lower))+
  geom_line(aes(y = coeff.upper))+
  ylab("Regression coefficient")+
  xlab("Date")+
  geom_ribbon(aes(ymin=coeff.lower, ymax=coeff.upper),alpha=0.09, fill = "blue")+
  theme_bw()+
  theme(text= element_text(size = 16))
```



```{r}
H29%>%
  ggplot(aes(x=Year, y=logTN, col=Month))+
  geom_point()


H29%>%filter(Month==2 | Month==1)%>%
  ggplot(aes(x=logq, y=logTN))+
  geom_point()+
  geom_smooth(method="lm")

H29%>%filter(Month==2 | Month==1)->H29_1_2

mod1_2<-lm(logTN~logq, data=H29_1_2)
summary(mod1_2)

H29%>%filter(Month==8 & Year <2005)->H29_8_9

mod8_9<-lm(logTN~logq, data=H29_8_9)
summary(mod8_9)



H29%>%filter(Month==8 & Year<2005)%>%
  ggplot(aes(x=logq, y=logTN))+
  geom_point()+
  geom_smooth(method="lm")
```

